# DAON 여름방학 파이썬 스터디 4회차 과제

#### 1. <파일 저장 형식> 'n회차_이름_과제'으로 저장하여 보내주세요!!(꼭 지켜주세요) 
#### 2. 못 풀고 끄적인 흔적이라도 남겨주셔도 괜찮아요! 나중에 꼭 다시 풀어주세요!!
#### 3. 모든 결과를 출력해 주세요. 

In [4]:
import pandas as pd
import numpy as np

# <1번>

`radius = np.array([1,3,5,6,7])`
#### 위 radius 의 요소를 반지름으로 하는 원의 넓이를 구하여 area 라는 array 에 추가하는 코드를 작성해주세요.
#### 파이 값은 3으로 합니다.

In [108]:
radius = np.array([1,3,5,6,7])
ar = []
for r in radius:
    ar.append(r*r*3)
area = np.array([ar])
area

array([[  3,  27,  75, 108, 147]])

# <2번>

#### (1) 2번째 행을 2차원 배열에서 추출하시오
#### (2) '7'이라는 요소를 2차원 배열에서 추출하시오

In [109]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
a[1,]

array([3, 4, 5])

In [111]:
a[2,1]

7

# <3번>

#### 아래와 과 같은 데이터프레임을 만들어보세요! (무심코 shift+enter 누르면 없어지니까 새 셀을 추가해서 그걸 보고 만들어주세요!)

In [44]:
# 여기 셀은 실행 시키지마세요 !

Name Belong  Age Gender
0  임종언     다온   25      남
1  배유나     다온   23      여
2  이현빈     다온   22      여
3  김보현     경통   21      여
4  홍재성     한빛   21      남

In [5]:
# 여기서 부터 답안코드 작성해주시면 됩니다

study = pd.DataFrame({
    'Name':['임종언','배유나','이현빈','김보현','홍재성'],
    'Bolong':['다온','다온','다온','경통','한빛'],
    'Age':[25,23,22,21,21],
    'Gender':['남','여','여','여','남']
})
study

Name Bolong  Age Gender
0  임종언     다온   25      남
1  배유나     다온   23      여
2  이현빈     다온   22      여
3  김보현     경통   21      여
4  홍재성     한빛   21      남

# <4번>

#### 위의 데이터 프레임에서 Gender 열을 삭제하고 자신의 정보를 데이터프레임에 추가하세요

In [6]:
study.drop('Gender',axis=1,inplace=True)
study

Name Bolong  Age
0  임종언     다온   25
1  배유나     다온   23
2  이현빈     다온   22
3  김보현     경통   21
4  홍재성     한빛   21

In [7]:
a_study = pd.DataFrame({
    'Name':['유광열'],
    'Bolong':['경통'],
    'Age':['20']
})
a_study

Name Bolong Age
0  유광열     경통  20

In [8]:
study = study.append(a_study).reset_index()
study

index Name Bolong Age
0      0  임종언     다온  25
1      1  배유나     다온  23
2      2  이현빈     다온  22
3      3  김보현     경통  21
4      4  홍재성     한빛  21
5      0  유광열     경통  20

# <5번>

#### 위의 데이터 프레임에 HomeTown 열을 추가하고 고향을 추가하세요 [멘토들의 고향은 경기, 광주, 충북, 울산, 서울입니다^^]

In [9]:
study['HomeTown'] = ['경기','광주','충북','울산','서울','서울']
study

index Name Bolong Age HomeTown
0      0  임종언     다온  25       경기
1      1  배유나     다온  23       광주
2      2  이현빈     다온  22       충북
3      3  김보현     경통  21       울산
4      4  홍재성     한빛  21       서울
5      0  유광열     경통  20       서울

# <6번>

#### 위의 김보현의 'Belong' 을 '없음'로 바꿔주세요

In [10]:
study['Bolong'][3]='없음'
study

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


index Name Bolong Age HomeTown
0      0  임종언     다온  25       경기
1      1  배유나     다온  23       광주
2      2  이현빈     다온  22       충북
3      3  김보현     없음  21       울산
4      4  홍재성     한빛  21       서울
5      0  유광열     경통  20       서울

# <7번>

#### gapminder.tsv 데이터는 tab으로 구분되어 있는 데이터 입니다. 구글링을 통해 `sep='??'` 에 들어갈 알맞은 코드를 넣어 gapminder를 출력해보세요

In [42]:
gapminder=pd.read_csv('gapminder.tsv',sep='/t')
gapminder

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


country\tcontinent\tyear\tlifeExp\tpop\tgdpPercap
0     Afghanistan\tAsia\t1952\t28.801\t8425333\t779....
1     Afghanistan\tAsia\t1957\t30.332\t9240934\t820....
2     Afghanistan\tAsia\t1962\t31.997\t10267083\t853...
3     Afghanistan\tAsia\t1967\t34.02\t11537966\t836....
4     Afghanistan\tAsia\t1972\t36.088\t13079460\t739...
5     Afghanistan\tAsia\t1977\t38.438\t14880372\t786...
6     Afghanistan\tAsia\t1982\t39.854\t12881816\t978...
7     Afghanistan\tAsia\t1987\t40.822\t13867957\t852...
8     Afghanistan\tAsia\t1992\t41.674\t16317921\t649...
9     Afghanistan\tAsia\t1997\t41.763\t22227415\t635...
10    Afghanistan\tAsia\t2002\t42.129\t25268405\t726...
11    Afghanistan\tAsia\t2007\t43.828\t31889923\t974...
12    Albania\tEurope\t1952\t55.23\t1282697\t1601.05...
13    Albania\tEurope\t1957\t59.28\t1476505\t1942.28...
14    Albania\tEurope\t1962\t64.82\t1728137\t2312.88...
15    Albania\tEurope\t1967\t66.22\t1984060\t2760.19...
16    Albania\tEurope\t1972\t67.69\t2263554\t3313.42...
17    Albania\tEurope\t1977\t68.93\t2509048\t3533.00391
18    Albania\tEurope\t1982\t70.42\t2780097\t3630.88...
19      Albania\tEurope\t1987\t72\t3075321\t3738.932735
20    Albania\tEurope\t1992\t71.581\t3326498\t2497.4...
21    Albania\tEurope\t1997\t72.95\t3428038\t3193.05...
22    Albania\tEurope\t2002\t75.651\t3508512\t4604.2...
23    Albania\tEurope\t2007\t76.423\t3600523\t5937.0...
24    Algeria\tAfrica\t1952\t43.077\t9279525\t2449.0...
25    Algeria\tAfrica\t1957\t45.685\t10270856\t3013....
26    Algeria\tAfrica\t1962\t48.303\t11000948\t2550....
27    Algeria\tAfrica\t1967\t51.407\t12760499\t3246....
28    Algeria\tAfrica\t1972\t54.518\t14760787\t4182....
29    Algeria\tAfrica\t1977\t58.014\t17152804\t4910....
...                                                 ...
1674  Yemen, Rep.\tAsia\t1982\t49.113\t9657618\t1977...
1675  Yemen, Rep.\tAsia\t1987\t52.922\t11219340\t197...
1676  Yemen, Rep.\tAsia\t1992\t55.599\t13367997\t187...
1677  Yemen, Rep.\tAsia\t1997\t58.02\t15826497\t2117...
1678  Yemen, Rep.\tAsia\t2002\t60.308\t18701257\t223...
1679  Yemen, Rep.\tAsia\t2007\t62.698\t22211743\t228...
1680  Zambia\tAfrica\t1952\t42.038\t2672000\t1147.38...
1681  Zambia\tAfrica\t1957\t44.077\t3016000\t1311.95...
1682  Zambia\tAfrica\t1962\t46.023\t3421000\t1452.72...
1683  Zambia\tAfrica\t1967\t47.768\t3900000\t1777.07...
1684  Zambia\tAfrica\t1972\t50.107\t4506497\t1773.49...
1685  Zambia\tAfrica\t1977\t51.386\t5216550\t1588.68...
1686  Zambia\tAfrica\t1982\t51.821\t6100407\t1408.67...
1687  Zambia\tAfrica\t1987\t50.821\t7272406\t1213.31...
1688   Zambia\tAfrica\t1992\t46.1\t8381163\t1210.884633
1689  Zambia\tAfrica\t1997\t40.238\t9417789\t1071.35...
1690  Zambia\tAfrica\t2002\t39.193\t10595811\t1071.6...
1691  Zambia\tAfrica\t2007\t42.384\t11746035\t1271.2...
1692  Zimbabwe\tAfrica\t1952\t48.451\t3080907\t406.8...
1693  Zimbabwe\tAfrica\t1957\t50.469\t3646340\t518.7...
1694  Zimbabwe\tAfrica\t1962\t52.358\t4277736\t527.2...
1695  Zimbabwe\tAfrica\t1967\t53.995\t4995432\t569.7...
1696  Zimbabwe\tAfrica\t1972\t55.635\t5861135\t799.3...
1697  Zimbabwe\tAfrica\t1977\t57.674\t6642107\t685.5...
1698  Zimbabwe\tAfrica\t1982\t60.363\t7636524\t788.8...
1699  Zimbabwe\tAfrica\t1987\t62.351\t9216418\t706.1...
1700  Zimbabwe\tAfrica\t1992\t60.377\t10704340\t693....
1701  Zimbabwe\tAfrica\t1997\t46.809\t11404948\t792....
1702  Zimbabwe\tAfrica\t2002\t39.989\t11926563\t672....
1703  Zimbabwe\tAfrica\t2007\t43.487\t12311143\t469....

[1704 rows x 1 columns]

# <추가문제> #

#### `year = int(input())` 를 사용해 year에 연도를 할당한 후, 그 연도가 평년인지 윤년인지 구하는 알고리즘을 만들어보세요.


* 조건 1 : 연도가 4의 배수이면 윤년이고 그 외에는 평년입니다.
* 조건 2 : 조건 1 에서 100의 배수이면 평년이고, 400의 배수이면 윤년입니다.
* 조건 3 : 만약 연도가 1년부터 2999년 사이에 존재하지 않으면 '오류'를 출력하세요.

* 예시 1 : 2400은 4와 100의 배수이지만 400의 배수도 되기 때문에 윤년입니다.
* 예시 2 : 2020은 4의 배수는 맞지만 100의 배수가 아니므로 윤년입니다.

In [38]:
year = int(input())
if year%4 == 0 and year%100 != 0:
    print(str(year) + '은 4의 배수는 맞지만 100의 배수가 아니므로 윤년입니다.')
elif year%4 ==0 and year%400==0:
    print(str(year) + '은 4와 100의 배수는 맞지만 400의 배수도 되기 때문에 윤년입니다.')
elif 1>year or year>2999:
    print('오류입니다.')
else:
    print('평년입니다.')

2400
2400은 4와 100의 배수는 맞지만 400의 배수도 되기 때문에 윤년입니다.
